clear all;
clf;
PREPATH = 'Case_2300_'; % load appropriate file directory


Egen = 0; % set initial energy generated equal to zero 
TotalP = 0;
for c = 1:17 
    load([PREPATH num2str(c)]); % for loop for each frame of the oscilloscope readings

    R = 1.079e6; % internal resistance of oscilloscope
    Rho = 1.293; % density of the air

    % wind speed data
    s = linspace(0,85,85); 
    v = [0,0,0,0,0,0,0,0,0,0,0,0,0,0.1849,0.5236,0.5486,0.6509,0.7556,0.8325,0.9547,1.0719,1.1515,1.2821,1.3309,1.3957,1.4559,1.5006,1.5261,1.5336,1.5599,1.5583,1.5552,1.5425,1.5639,1.5350,1.5390,1.5157,1.5171,1.4909,1.4974,1.4563,1.4479,1.4525,1.4641,1.4433,1.4354,1.4128,1.4148,1.4148,1.4066,1.4093,1.3975,1.3969,1.3974,1.3922,1.3950,1.4020,1.3830,1.4004,1.3950,1.4006,1.4029,1.4032,1.4001,1.4024,1.4027,1.3696,1.3636,1.3074,1.3375,1.2442,1.0862,1.0619,1.0103,0.9056,0.8512,0.7158,0.6693,0.5343,0.4395,0.1260,0,0,0,0];
 
    figure(1); % plot data on the same figure
    axis([0 85 0 1.5])

    yyaxis left
    % setting time space for each frame
    x1 = (c-1)*5; 
    x2 = c*5;
    n = length(A);
    t = linspace(x1,x2,n);
    V = plot(t,A,'b-','Marker','none'); % plot for voltage against time
    xlim([0 85]);
    ylim([0 2]);
    hold on;

    yyaxis right
    W = plot(s,v,'k-','Marker','none'); % plot for wind speed against time
    xlim([0 85]);
    ylim([-0.4 1.6]);

    grid on; axis tight; set(gca,'fontsize',14);

    yyaxis left
    xlabel('Time / s','interpreter','latex');
    ylabel('Voltage / V','interpreter','latex');

    yyaxis right
    ylabel('Wind Speed / $ms^-1$','interpreter','latex');

    
    Egen = Egen + sum(A.^2/1e6).*(1/1300); % calculating the energy generated by the harvester
    Ewind = 0.14 * 0.45 *Rho * sum(v.^3) /2; % calculating the enrgy provided by the wind
    Efficiency = (Egen/Ewind)*100; % calculating the effiency of the harvester

    title('Voltage Output and Wind Speed over Time for case 2300 - System B','Interpreter','latex');
    textSubtitle = ['Total Energy Output = ' num2str(Egen) 'J','   Total Energy Input = ' num2str(Ewind) 'J','   Efficiency = ' num2str(Efficiency) '%'] ;
    subtitle(textSubtitle);
    lbl = [V W];
    legend(lbl,'Voltage Output','Wind Speed');


    TotalP = TotalP+ sum(A.^2/1e6)
end
